name: agridirect
description: AI-powered agricultural assistance app with disease detection, crop prediction, and farming tools.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core UI and Animation Dependencies
  animated_text_kit: ^4.2.2
  audioplayers: ^6.1.0
  awesome_notifications: ^0.10.1
  battery_plus: ^6.0.2
  cached_network_image: ^3.4.1
  calendar_date_picker2: ^1.1.7
  camera: ^0.11.0
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.2
  dio: ^5.7.0
  equatable: ^2.0.5
  file_picker: ^8.1.2
  fl_chart: ^0.69.0
  flutter_bloc: ^8.1.6
  flutter_cache_manager: ^3.4.1
  flutter_dotenv: ^5.1.0
  flutter_form_builder: ^10.1.0
  flutter_local_notifications: ^17.2.3
  flutter_polyline_points: ^2.1.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10
  form_builder_validators: ^11.2.0
  freezed_annotation: ^2.4.4
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  go_router: ^14.2.7
  google_maps_flutter: ^2.9.0
  google_sign_in: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  hydrated_bloc: ^9.1.5
  image: ^4.2.0
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  internet_connection_checker: ^3.0.1  # Fixed version
  intl: ^0.20.2
  json_annotation: ^4.9.0
  location: ^7.0.0
  logger: ^2.4.0
  lottie: ^3.1.2
  open_file: ^3.5.4
  package_info_plus: ^8.0.2
  path: ^1.9.0
  path_provider: ^2.1.4
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pie_chart: ^5.4.0
  pretty_dio_logger: ^1.4.0
  printing: ^5.13.2
  provider: ^6.1.1
  reactive_forms: ^17.0.1
  retry: ^3.1.2
  sensors_plus: ^6.0.1
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  syncfusion_flutter_charts: ^27.1.48
  table_calendar: ^3.1.2
  
  # ML dependencies - cross-platform alternative
  google_ml_kit: ^0.18.0
  
  url_launcher: ^6.3.0
  uuid: ^4.5.0
  vibration: ^3.0.0
  video_player: ^2.9.1
  weather: ^3.1.1

  # Firebase dependencies - Compatible versions
  firebase_core: ^2.32.0
  firebase_auth: ^4.15.0
  firebase_analytics: ^10.10.0
  firebase_crashlytics: ^3.5.7
  firebase_messaging: ^14.9.0
  firebase_remote_config: ^4.4.0
  firebase_storage: ^11.7.0
  cloud_firestore: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Testing, Linting and Code Generation
  bloc_test: ^9.1.7
  build_runner: ^2.4.12
  flutter_gen: ^5.7.0
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.1
  freezed: ^2.5.7
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  network_image_mock: ^2.1.1
  test: ^1.25.8

# Dependency overrides to ensure compatibility
dependency_overrides:
  # Ensure proper JS interop for web builds
  web: ^1.0.0
  js: ^0.7.1
  # Force intl version compatibility across all packages
  intl: ^0.20.2

flutter:
  uses-material-design: true

  # Assets Configuration
  assets:
    # Images
    - assets/images/
    - assets/images/onboarding/
    - assets/images/backgrounds/
    - assets/images/placeholders/

    # Icons (organized by category)
    - assets/images/icons/
    - assets/images/icons/weather/
    - assets/images/icons/crops/
    - assets/images/icons/tools/
    - assets/images/icons/diseases/
    - assets/images/icons/fertilizers/
    - assets/images/icons/pests/
    - assets/images/icons/navigation/

    # ML Models & Data - Complete Structure
    - assets/models/
    - assets/models/disease_detection/
    - assets/models/crop_prediction/

    # Individual ML Model Files
    - assets/models/plant_disease_model.tflite
    - assets/models/growth_stage_model.tflite
    - assets/models/crop_yield_model.tflite
    - assets/models/soil_type_model.tflite
    - assets/models/soil_moisture_model.tflite
    - assets/models/soil_ph_model.tflite
    - assets/models/pest_detection_model.tflite
    - assets/models/beneficial_insects_model.tflite
    - assets/models/pest_damage_model.tflite

    # Labels and Classification Files
    - assets/labels/
    - assets/models/disease_labels.txt
    - assets/models/crop_type_labels.txt
    - assets/models/growth_stage_labels.txt
    - assets/models/soil_type_labels.txt
    - assets/models/pest_labels.txt
    - assets/models/beneficial_labels.txt
    - assets/models/damage_labels.txt

    # Additional Data Files
    - assets/data/
    - assets/data/crops/
    - assets/data/weather/
    - assets/data/diseases/

    # Animations
    - assets/animations/
    - assets/animations/lottie/

    # Configuration Files
    - .env
    - .env.production
    - .env.staging

    # Documentation
    - assets/docs/
    - assets/docs/user_guide/

  # OPTIONAL: Custom fonts (uncomment when font files are available)
  # fonts:
  #   # Primary Font Family - Modern and Clean
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter/Inter-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Inter/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter/Inter-Bold.ttf
  #         weight: 700

  #   # Secondary Font Family - For Headers
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins/Poppins-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Poppins/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins/Poppins-Bold.ttf
  #         weight: 700

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"

# Native Splash Screen Configuration
flutter_native_splash:
  color: "#4CAF50"
  image: assets/images/splash_logo.png
  branding: assets/images/branding.png
  color_dark: "#1B5E20"
  image_dark: assets/images/splash_logo_dark.png
  branding_dark: assets/images/branding_dark.png
  android_12:
    image: assets/images/splash_logo_android12.png
    icon_background_color: "#4CAF50"
    image_dark: assets/images/splash_logo_android12_dark.png
    icon_background_color_dark: "#1B5E20"
  web: false

# Flutter Gen Configuration
flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

# Internationalization Configuration
flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false