name: agridirect
description: AI-powered agricultural assistance app with disease detection, crop prediction, and farming tools.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  lottie: ^3.3.1

  # State Management
  provider: ^6.0.5
  flutter_bloc: ^9.1.1

  # Navigation
  go_router: ^16.0.0

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.0

  # Networking
  http: ^1.1.0
  dio: ^5.3.2
  connectivity_plus: ^6.1.4
  internet_connection_checker: ^3.0.1

  # Local Storage
  shared_preferences: ^2.2.1
  sqflite: ^2.3.0

  # Location & Maps
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.4.0

  # Camera & Image
  image_picker: ^1.0.4
  camera: ^0.11.2
  image: ^4.5.4

  # ML & AI
  tflite_flutter: ^0.11.0
  tflite_flutter_helper: ^0.2.0 # ⚠️ Discontinued — migrate soon

  # Permissions
  permission_handler: ^12.0.1

  # Utils
  intl: ^0.20.2
  url_launcher: ^6.1.12
  package_info_plus: ^8.3.0
  device_info_plus: ^11.5.0

  # Charts & Data Visualization
  fl_chart: ^1.0.0

  # Calendar & DateTime
  table_calendar: ^3.0.9

  # Environment Variables
  flutter_dotenv: ^5.1.0

  # Notifications
  flutter_local_notifications: ^19.4.0

  # Weather & API Integration
  weather: ^3.1.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/weather/
    - assets/images/icons/crops/
    - assets/images/icons/tools/
    - assets/images/icons/diseases/
    - assets/models/
    - assets/labels/
    - assets/data/
    - assets/fonts/
    - .env

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
